server:
  port: 8761

spring:
  application:
    name: learn-service-registry

learn:
  serviceRegistry:
    username: ${NAME}
    password: ${PASSWORD}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false